services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  HDNET\CdnFastly\:
    resource: '../Classes/*'

  HDNET\CdnFastly\EventListener\FastlyClearCacheListener:
    tags:
      - name: event.listener
